return {{
    href = "https://global.oup.com/academic/product/the-nicomachean-ethics-9780199213610",
    title_fmt = '<span lang="grc">Ἠθικὰ Νικομάχεια</span>'
        .. "<br />(The Nicomachean<br />Ethics)",
    title = '<span lang="grc">Ἠθικὰ Νικομάχεια</span> (The Nicomachean Ethics)',
    id = "the-nicomachean-ethics",
    cover = "the_nicomachean_ethics.jpg",
    author = "Aristotle",
}, {
    href = "https://www.harpercollins.com/products/wuthering-heights-collins-classics-emily-bronte",
    title_fmt = "Wuthering heights",
    title = "Wuthering heights",
    id = "wuthering-heights",
    cover = "wuthering_heights.jpg",
    author = "Emily Brontë",
}, {
    href = "https://www.rizzolilibri.it/libri/alcesti/",
    title_fmt = '<span lang="grc">Ἄλκηστις</span><br />(Alcestis)',
    title = '<span lang="grc">Ἄλκηστις</span> (Alcestis)',
    id = "alcestis",
    cover = "alcesti.jpg",
    author = "Euripides",
}, {
    href = "https://www.williamcollinsbooks.co.uk/products/mere-christianity-c-s-lewis-9780007332243/",
    title_fmt = "Notes from the<br />underground",
    title = "Notes from the underground",
    id = "notes-from-the-underground",
    cover = "ricordi_dal_sottosuolo.jpg",
    author = "Fyodor Dostoevsky",
}, {
    href = "https://www.penguinrandomhouse.com/books/241840/the-brothers-karamazov-by-fyodor-dostoevsky-translated-by-richard-pevear-and-larissa-volokhonsky-introduction-by-malcolm-jones/",
    title_fmt = "The brothers<br />Karamazov",
    title = "The brothers Karamazov",
    id = "the-brothers-karamazov",
    cover = "the_brothers_karamazov.jpg",
    author = "Fyodor Dostoevsky",
}, {
    href = "https://www.penguin.co.uk/books/57587/siddhartha-by-hermann-hesse-intro--paulo-coelho/9780141189574",
    title_fmt = "Siddhartha",
    title = "Siddhartha",
    id = "siddhartha",
    cover = "siddhartha.png",
    author = "Hermann Hesse",
}, {
    href = "https://store.dailywire.com/products/the-kingdom-of-cain",
    title_fmt = "The kingdom of Cain",
    title = "The kingdom of Cain",
    id = "the-kingdom-of-cain",
    cover = "the_kingdom_of_cain.jpg",
    author = "Andrew Klavan",
}, {
    href = "https://store.dailywire.com/products/the-kingdom-of-cain",
    title_fmt = "Light of the mind,<br />light of the world",
    title = "Light of the mind, light of the world",
    id = "light-of-the-mind-light-of-the-world",
    cover = "light_of_the_mind_light_of_the_world.jpg",
    author = "Spencer A. Klavan",
}, {
    href = "https://www.williamcollinsbooks.co.uk/products/mere-christianity-c-s-lewis-9780007332243/",
    title_fmt = "Mere Christianity",
    title = "Mere Christianity",
    id = "mere-christianity",
    cover = "mere_christianity.jpg",
    author = "C. S. Lewis",
}, {
    href = "https://www.harpercollins.com/products/out-of-the-silent-planet-c-s-lewis",
    title_fmt = "Out of the silent planet",
    title = "Out of the silent planet",
    id = "out-of-the-silent-planet",
    cover = "out_of_the_silent_planet.jpg",
    author = "C. S. Lewis",
}, {
    href = "https://www.williamcollinsbooks.co.uk/products/the-screwtape-letters-letters-from-a-senior-to-a-junior-devil-c-s-lewis-signature-classic-c-s-lewis-9780007461240/",
    title_fmt = "The Screwtape<br />letters",
    title = "The Screwtape letters",
    id = "the-screwtape-letters",
    cover = "the_screwtape_letters.jpg",
    author = "C. S. Lewis",
}, {
    href = "https://www.harpercollins.com/products/the-call-of-the-wild-collins-classics-jack-london",
    title_fmt = "The call<br />of the wild",
    title = "The call of the wild",
    id = "the-call-of-the-wild",
    cover = "the_call_of_the_wild.jpg",
    author = "Jack London",
}, {
    href = "https://www.harpercollins.com/products/white-fang-collins-classics-jack-london",
    title_fmt = "White fang",
    title = "White fang",
    id = "white-fang",
    cover = "white_fang.jpg",
    author = "Jack London",
}, {
    href = "https://www.penguin.co.uk/books/57033/animal-farm-by-orwell-george/9780241453865",
    title_fmt = "Animal farm",
    title = "Animal farm",
    id = "animal-farm",
    cover = "animal_farm.jpg",
    author = "George Orwell",
}, {
    href = "https://www.jordanbpeterson.com/12-rules-for-life/",
    title_fmt = "12 rules for life",
    title = "12 rules for life",
    id = "12-rules-for-life",
    cover = "12_rules_for_life.jpg",
    author = "Jordan B. Peterson",
}, {
    href = "https://www.jordanbpeterson.com/beyond-order/",
    title_fmt = "Beyond order",
    title = "Beyond order",
    id = "beyond-order",
    cover = "beyond_order.jpg",
    author = "Jordan B. Peterson",
}, {
    href = "https://global.oup.com/academic/product/symposium-9780199540198",
    title_fmt = '<span lang="grc">Συμπόσιον</span><br />(The Symposium)',
    title = '<span lang="grc">Συμπόσιον</span> (The Symposium)',
    id = "the-symposium",
    cover = "symposium.jpg",
    author = "Plato",
}, {
    href = "https://www.oscarmondadori.it/libri/fedro-platone/",
    title_fmt = '<span lang="grc">Φαῖδρος</span><br />(Phaedrus)',
    title = '<span lang="grc">Φαῖδρος</span> (Phaedrus)',
    id = "phaedrus",
    cover = "fedro.jpg",
    author = "Plato",
}, {
    href = "https://www.ragazzimondadori.it/libri/il-piccolo-principe-antoine-de-saint-exupery-9788804648826/",
    title_fmt = '<span lang="fr">Le petit prince</span><br />(The little prince)',
    title = '<span lang="fr">Le petit prince</span>',
    id = "the-little-prince",
    cover = "il_piccolo_principe.jpg",
    author = "Antoine de Saint-Exupéry",
}, {
    href = "https://www.lafeltrinelli.it/edipo-re-testo-greco-a-libro-sofocle/e/9788807900471",
    title_fmt = '<span lang="grc">Οἰδίπους Τύραννος</span><br />(Oedipus Rex)',
    title = '<span lang="grc">Οἰδίπους Τύραννος</span>',
    id = "oedipus-rex",
    cover = "edipo_re.jpg",
    author = "Sophocles",
}, {
    href = "https://global.oup.com/academic/product/the-merchant-of-venice-the-oxford-shakespeare-9780199535859",
    title_fmt = "The merchant<br />of Venice",
    title = 'The merchant of Venice',
    id = "the-merchant-of-venice",
    cover = "the_merchant_of_venice.jpg",
    author = "William Shakespeare",
}, {
    href = "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0208",
    title_fmt = '<span lang="grc">Ἀπομνημονεύματα</span><br />(Memorabilia)',
    title = '<span lang="grc">Ἀπομνημονεύματα</span> (Memorabilia)',
    id = "memorabilia",
    cover = "memorabilia.jpg",
    author = "Xenophon",
}}
